name: Django CI
on:
  push:
    branches: ["staging"]

jobs:
  build:
    runs-on: windows-10
    container: python:3.11-slim
    steps:
      - name: Clone from github
        uses: actions/checkout@v3
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run the test
        run: |
          python manage.py test
          